const ingredients = {
  en: {
    honey: "Honey",
    tableSugar: "Table Sugar",
    customIngredient: "Custom Ingredient",
    water: "Water",
    juice: "Juice",
    apples: "Apples",
    appleJuice: "Apple Juice",
    apricot: "Apricot",
    banana: "Banana",
    blackberry: "Blackberry",
    blueberry: "Blueberry",
    boysenberry: "Boysenberry",
    cantaloupe: "Cantaloupe",
    carrot: "Carrot",
    cherrySweet: "Cherry, Sweet",
    cherryTart: "Cherry, Tart",
    cranberry: "Cranberry",
    cranberryJuice: "Cranberry Juice",
    currantBlack: "Currant, Black",
    currantRed: "Currant, Red",
    datesDried: "Dates, Dried",
    elderberry: "Elderberry",
    figs: "Figs",
    figsDried: "Figs, Dried",
    gooseberry: "Gooseberry",
    grapefruit: "Grapefruit",
    grapefruitJuice: "Grapefruit Juice",
    grapesConcord: "Grapes, Concord",
    grapeJuicePurple: "Grape Juice, Purple",
    grapeJuiceWhite: "Grape Juice, White",
    guava: "Guava",
    honeydewMelon: "Honeydew Melon",
    jackfruit: "Jackfruit",
    kiwi: "Kiwi",
    lemonJuice: "Lemon Juice",
    limeJuice: "Lime Juice",
    lychee: "Lychee",
    mango: "Mango",
    mapleSyrup: "Maple Syrup",
    mulberry: "Mulberry",
    nectarine: "Nectarine",
    onion: "Onion",
    orangeJuice: "Orange Juice",
    papaya: "Papaya",
    passionFruit: "Passion  Fruit",
    peaches: "Peaches",
    pear: "Pear",
    persimmon: "Persimmon",
    pineapple: "Pineapple",
    plum: "Plum",
    pomegranate: "Pomegranate",
    pricklyPear: "Prickly Pear",
    prunes: "Prunes",
    raisins: "Raisins",
    raspberry: "Raspberry",
    rhubarb: "Rhubarb",
    strawberry: "Strawberry",
    tangerine: "Tangerine",
    tomato: "Tomato",
    tomatoJuice: "Tomato Juice",
    watermelon: "Watermelon",
  },
  de: {
    honey: "Honig",
    tableSugar: "Haushaltszucker",
    customIngredient: "Eigene Zutat",
    water: "Wasser",
    juice: "Saft",
    apples: "Apfel",
    appleJuice: "Apfelsaft",
    apricot: "Aprikose",
    banana: "Banane",
    blackberry: "Brombeere",
    blueberry: "Blaubeere",
    boysenberry: "Boysenbeere",
    cantaloupe: "Cantaloupe-Melone",
    carrot: "Karrotte",
    cherrySweet: "Süßkirsche",
    cherryTart: "Sauerkirsche",
    cranberry: "Cranberry",
    cranberryJuice: "Cranberrysaft",
    currantBlack: "Johannisbeere, Schwarz",
    currantRed: "Johannisbeere, Rot",
    datesDried: "Dattel, getrocknet",
    elderberry: "Holunderbeere",
    figs: "Feige",
    figsDried: "Feige, getrocknet",
    gooseberry: "Stachelbeere",
    grapefruit: "Grapefruit",
    grapefruitJuice: "Grapefruitsaft",
    grapesConcord: "Trauben, Concord",
    grapeJuicePurple: "Traubensaft, rot",
    grapeJuiceWhite: "Traubensaft, weiß",
    guava: "Guave",
    honeydewMelon: "Honigmelone",
    jackfruit: "Jackfrucht",
    kiwi: "Kiwi",
    lemonJuice: "Zitronensaft",
    limeJuice: "Limettensaft",
    lychee: "Litschi",
    mango: "Mango",
    mapleSyrup: "Ahornsirup",
    mulberry: "Maulbeere",
    nectarine: "Nektarine",
    onion: "Zwiebel",
    orangeJuice: "Orangensaft",
    papaya: "Papaya",
    passionFruit: "Maracuja",
    peaches: "Pfirsich",
    pear: "Birne",
    persimmon: "Kaki",
    pineapple: "Ananas",
    plum: "Pflaume",
    pomegranate: "Granatapfel",
    pricklyPear: "Kaktusfeige",
    prunes: "Trockenpflaumen",
    raisins: "Rosinen",
    raspberry: "Himbeere",
    rhubarb: "Rhabarber",
    strawberry: "Erdbeere",
    tangerine: "Mandarine",
    tomato: "Tomate",
    tomatoJuice: "Tomatensaft",
    watermelon: "Wassermelone",
  }
};

export const ingredientTranslations = [ingredients.en, ingredients.de];
