const nutes = {
  en: {
    nutrients: {
      fermO: "Fermaid O",
      fermK: "Fermaid K",
      dap: "DAP",
      goFerm: "Go Ferm",
    },
    nutesHeading: "Nutrient Calculator",
    yeastBrand: "Yeast Brand",
    yeastStrain: "Yeast Strain",
    nuteVolume: "Volume",
    nuteSgLabel: "Specific Gravity",
    offset: "Offset PPM",
    n2Requirement: {
      label: "Nitrogen Requirement",
      low: "Low",
      medium: "Medium",
      high: "High",
      veryHigh: "Very High",
    },
    nuteSchedules: {
      label: "Preferred Schedule",
      tbe: "TBE (All Three)",
      tosna: "TOSNA (Fermaid O Only)",
      justK: "Fermaid K Only",
      dap: "DAP Only",
      oAndk: "Fermaid O and K",
      oAndDap: "Fermaid O and DAP",
      kAndDap: "Fermaid K and DAP",
    },
    targetYan: "Target YAN",
    numberOfAdditions: "Number of Additions",
    yeastAmount: "Yeast Amount (g)",
    buttonLabels: {
      advanced: "Advanced Nutrition",
      next: "Next",
      back: "Back",
    },
    advancedNutrition: {
      label: "Advanced Nutrition",
      yanContribution: "Edit YAN Contribution",
      yanFromSource: "Edit YAN From Source",
    },
    nuteResults: {
      label: "Nutrient Calculator Results",
      gfTypes: {
        gf: "Go-Ferm",
        gfProtect: "Go-Ferm Protect",
        gfSterol: "Go-Ferm Sterol Flash",
        none: "None",
      },
      gfWater: "Water for Go-Ferm",
      sb: "1/3 Sugar Break",
      sideLabels: {
        maxGpl: "Max g/L",
        ppmYan: "PPM YAN",
        totalGrams: "Total Grams",
        perAddition: "Amount per Addition",
        totalYan: "Total YAN",
        remainingYan: "Remaining YAN",
      },
    },
  },
  de: {
    nutrients: {
      fermO: "Fermaid O",
      fermK: "Fermaid K",
      dap: "DAP",
      goFerm: "Go Ferm",
    },
    nutesHeading: "Nährstoffrechner",
    yeastBrand: "Hefehersteller",
    yeastStrain: "Hefesorte",
    nuteVolume: "Volumen",
    nuteSgLabel: "Spezifische Dichte (SG)",
    offset: "PPM-Versatz",
    n2Requirement: {
      label: "Stickstoffbedarf",
      low: "Niedrig",
      medium: "Mittel",
      high: "Hoch",
      veryHigh: "Sehr Hoch",
    },
    nuteSchedules: {
      label: "Bevorzugter Nährstoffplan",
      tbe: "TBE (Alle drei)",
      tosna: "TOSNA (Nur Fermaid O)",
      justK: "Nur Fermaid K",
      dap: "Nur DAP",
      oAndk: "Fermaid O und K",
      oAndDap: "Fermaid O und DAP",
      kAndDap: "Fermaid K und DAP",
    },
    targetYan: "Ziel-YAN",
    numberOfAdditions: "Anzahl an Nährstoffgaben",
    yeastAmount: "Hefemenge (g)",
    buttonLabels: {
      advanced: "Erweiterte Einstellungen",
      next: "Weiter",
      back: "Zurück",
    },
    advancedNutrition: {
      label: "Erweiterte Einstellungen",
      yanContribution: "YAN-Anteil bearbeiten",
      yanFromSource: "YAN aus der Quelle bearbeiten",
    },
    nuteResults: {
      label: "Nährstoffrechner-Ergebnisse",
      gfTypes: {
        gf: "Go-Ferm",
        gfProtect: "Go-Ferm Protect",
        gfSterol: "Go-Ferm Sterol Flash",
        none: "Keine",
      },
      gfWater: "Wasser for Go-Ferm",
      sb: "1/3 Zuckergrenze",
      sideLabels: {
        maxGpl: "Max g/L",
        ppmYan: "PPM YAN",
        totalGrams: "Gesamt Gram",
        perAddition: "Menge pro Gabe",
        totalYan: "Gesamt YAN",
        remainingYan: "Verbleibende YAN",
      },
    },
  }
};

export const nutrientCalcTranslations = [nutes.en, nutes.de];
