const yeasts = {
  en: {
    lalvin: {
      label: "Lalvin",
      yeasts: {
        "182007": "18-2007",
        "1895C": "1895C",
        "71B": "71B",
        alchemyI: "ALCHEMY I",
        alchemyIi: "ALCHEMY II",
        alchemyIii: "ALCHEMY III",
        alchemyIv: "ALCHEMY IV",
        ba11: "BA11",
        bdx: "BDX",
        bm45: "BM 45",
        bm4X4: "BM 4x4",
        brl97: "BRL97",
        c: "C",
        clos: "CLOS",
        crossEvolution: "CROSS EVOLUTION",
        csm: "CSM",
        cvrp: "CVRP",
        cvw5: "CVW5",
        cy17: "CY17",
        cy3079Bourgoblanc: "CY3079 (BOURGOBLANC)",
        dv10: "DV10",
        ec1118: "EC1118",
        ec1118Organic: "EC1118 (ORGANIC)",
        enofermAmh: "ENOFERM AMH",
        enofermSyrah: "ENOFERM SYRAH",
        exoticsMosaic: "EXOTICS MOSAIC",
        exoticsNovello: "EXOTICS NOVELLO",
        fermivin3C: "FERMIVIN 3C",
        fermivin4F9: "FERMIVIN 4F9",
        fermivinA33: "FERMIVIN A33",
        fermivinMt48: "FERMIVIN MT48",
        fermivinPf6: "FERMIVIN PF6",
        icvD21: "ICV D21",
        icvD254: "ICV D254",
        icvD47: "ICV D47",
        icvD80: "ICV D80",
        icvGre: "ICV GRE",
        icvOkay: "ICV OKAY",
        icvSunrose: "ICV SUNROSE",
        iocBeFruits: "IOC BE FRUITS",
        iocBeThiols: "IOC BE THIOLS",
        k1V1116: "K1V1116",
        levulineBrg: "LEVULINE BRG",
        m83: "M83",
        msb: "MSB",
        mt: "MT",
        nbc: "NBC",
        nt116: "NT 116",
        nt202: "NT 202",
        nt50: "NT 50",
        oenofermBouquet: "OENOFERM BOUQUET",
        oenofermFreddo: "OENOFERM FREDDO",
        oenofermPinotype: "OENOFERM PINOTYPE",
        oenofermRiesling: "OENOFERM RIESLING",
        oenofermXThiol: "OENOFERM X-THIOL",
        oenofermXTreme: "OENOFERM X-TREME",
        persy: "PERSY",
        qa23: "QA23",
        rHst: "R-HST",
        r2: "R2",
        ra17: "RA17",
        rc212Bourgorouge: "RC212 (BOURGOROUGE)",
        rhone2056: "RHÔNE 2056",
        rhone2226: "RHÔNE 2226",
        rhone4600: "RHÔNE 4600",
        rp15: "RP15",
        sauvy: "SAUVY",
        sensy: "SENSY",
        steinberger: "STEINBERGER",
        svg: "SVG",
        tango: "TANGO",
        uvaferm43: "UVAFERM 43",
        uvafermCegEpernayIi: "UVAFERM CEG (EPERNAY II)",
        vin13: "VIN 13",
        vin2000: "VIN 2000",
        vitifermAlbaFriaOrganic: "VITIFERM ALBA FRIA (ORGANIC)",
        vitifermEspiritOrganic: "VITIFERM ESPIRIT (ORGANIC)",
        vitifermPinotAlbaOrganic: "VITIFERM PINOT ALBA (ORGANIC)",
        vitifermRubinoExtraOrganic: "VITIFERM RUBINO EXTRA (ORGANIC)",
        vitifermSauvageOrganic: "VITIFERM SAUVAGE (ORGANIC)",
        vitifermVulcanoOrganic: "VITIFERM VULCANO (ORGANIC)",
        vitilevure3001: "VITILEVURE 3001",
        vitilevure58W: "VITILEVURE 58W",
        vitilevureElixir: "VITILEVURE ELIXIR",
        vrb: "VRB",
        w15: "W15",
      },
    },
    fermentis: {
      label: "Fermentis",
      yeasts: { safAleUs05: "SafAle US-05" },
    },
    redStar: {
      label: "Red Star",
      yeasts: {
        cotesDesBlanc: "Cotes des Blanc",
        premierClassique: "Premier Classique",
        premierCuvee: "Premier Cuvee",
        premierRougePasteurRed: "Premier Rouge (Pasteur Red)",
      },
    },
    mangroveJack: {
      label: "Mangrove Jack",
      yeasts: {
        aw4: "AW4",
        bv7: "BV7",
        cl23: "CL23",
        cr51: "CR51",
        m02: "M02",
        m05: "M05",
        ma33: "MA33",
        r56: "R56",
        sn9: "SN9",
        vr21: "VR21",
      },
    },
    other: {
      label: "Other",
      yeasts: {
        otherLowNYeast: "Other Low N Yeast",
        otherMediumNYeast: "Other Medium N Yeast",
        otherHighNYeast: "Other High N Yeast",
        genericBeerYeast: "Generic Beer Yeast",
        kveikYeast: "Kveik Yeast",
      },
    },
  },
  de: {
    lalvin: {
      label: "Lalvin",
      yeasts: {
        "182007": "18-2007",
        "1895C": "1895C",
        "71B": "71B",
        alchemyI: "ALCHEMY I",
        alchemyIi: "ALCHEMY II",
        alchemyIii: "ALCHEMY III",
        alchemyIv: "ALCHEMY IV",
        ba11: "BA11",
        bdx: "BDX",
        bm45: "BM 45",
        bm4X4: "BM 4x4",
        brl97: "BRL97",
        c: "C",
        clos: "CLOS",
        crossEvolution: "CROSS EVOLUTION",
        csm: "CSM",
        cvrp: "CVRP",
        cvw5: "CVW5",
        cy17: "CY17",
        cy3079Bourgoblanc: "CY3079 (BOURGOBLANC)",
        dv10: "DV10",
        ec1118: "EC1118",
        ec1118Organic: "EC1118 (ORGANIC)",
        enofermAmh: "ENOFERM AMH",
        enofermSyrah: "ENOFERM SYRAH",
        exoticsMosaic: "EXOTICS MOSAIC",
        exoticsNovello: "EXOTICS NOVELLO",
        fermivin3C: "FERMIVIN 3C",
        fermivin4F9: "FERMIVIN 4F9",
        fermivinA33: "FERMIVIN A33",
        fermivinMt48: "FERMIVIN MT48",
        fermivinPf6: "FERMIVIN PF6",
        icvD21: "ICV D21",
        icvD254: "ICV D254",
        icvD47: "ICV D47",
        icvD80: "ICV D80",
        icvGre: "ICV GRE",
        icvOkay: "ICV OKAY",
        icvSunrose: "ICV SUNROSE",
        iocBeFruits: "IOC BE FRUITS",
        iocBeThiols: "IOC BE THIOLS",
        k1V1116: "K1V1116",
        levulineBrg: "LEVULINE BRG",
        m83: "M83",
        msb: "MSB",
        mt: "MT",
        nbc: "NBC",
        nt116: "NT 116",
        nt202: "NT 202",
        nt50: "NT 50",
        oenofermBouquet: "OENOFERM BOUQUET",
        oenofermFreddo: "OENOFERM FREDDO",
        oenofermPinotype: "OENOFERM PINOTYPE",
        oenofermRiesling: "OENOFERM RIESLING",
        oenofermXThiol: "OENOFERM X-THIOL",
        oenofermXTreme: "OENOFERM X-TREME",
        persy: "PERSY",
        qa23: "QA23",
        rHst: "R-HST",
        r2: "R2",
        ra17: "RA17",
        rc212Bourgorouge: "RC212 (BOURGOROUGE)",
        rhone2056: "RHÔNE 2056",
        rhone2226: "RHÔNE 2226",
        rhone4600: "RHÔNE 4600",
        rp15: "RP15",
        sauvy: "SAUVY",
        sensy: "SENSY",
        steinberger: "STEINBERGER",
        svg: "SVG",
        tango: "TANGO",
        uvaferm43: "UVAFERM 43",
        uvafermCegEpernayIi: "UVAFERM CEG (EPERNAY II)",
        vin13: "VIN 13",
        vin2000: "VIN 2000",
        vitifermAlbaFriaOrganic: "VITIFERM ALBA FRIA (ORGANIC)",
        vitifermEspiritOrganic: "VITIFERM ESPIRIT (ORGANIC)",
        vitifermPinotAlbaOrganic: "VITIFERM PINOT ALBA (ORGANIC)",
        vitifermRubinoExtraOrganic: "VITIFERM RUBINO EXTRA (ORGANIC)",
        vitifermSauvageOrganic: "VITIFERM SAUVAGE (ORGANIC)",
        vitifermVulcanoOrganic: "VITIFERM VULCANO (ORGANIC)",
        vitilevure3001: "VITILEVURE 3001",
        vitilevure58W: "VITILEVURE 58W",
        vitilevureElixir: "VITILEVURE ELIXIR",
        vrb: "VRB",
        w15: "W15",
      },
    },
    fermentis: {
      label: "Fermentis",
      yeasts: { safAleUs05: "SafAle US-05" },
    },
    redStar: {
      label: "Red Star",
      yeasts: {
        cotesDesBlanc: "Cotes des Blanc",
        premierClassique: "Premier Classique",
        premierCuvee: "Premier Cuvee",
        premierRougePasteurRed: "Premier Rouge (Pasteur Red)",
      },
    },
    mangroveJack: {
      label: "Mangrove Jack",
      yeasts: {
        aw4: "AW4",
        bv7: "BV7",
        cl23: "CL23",
        cr51: "CR51",
        m02: "M02",
        m05: "M05",
        ma33: "MA33",
        r56: "R56",
        sn9: "SN9",
        vr21: "VR21",
      },
    },
    other: {
      label: "Andere",
      yeasts: {
        otherLowNYeast: "Andere Hefe - Wenig Stickstoffbedarf",
        otherMediumNYeast: "Andere Hefe - Mittlerer Stickstoffbedarf",
        otherHighNYeast: "Andere Hefe - Hoher Stickstoffbedarf",
        genericBeerYeast: "Generische Bierhefe",
        kveikYeast: "Kveik-Hefe",
      },
    },
  }
};

export const yeastTranslations = [yeasts.en, yeasts.de];
