const PDF = {
  en: {
    PDF: {
      title: "Recipe PDF",
      pageTitle: "Recipe Sheet",
      totalVolume: "Total Volume",
      yeast: "Yeast",
      of: "of",
      with: "with",
      tempRange: "Temp Range",
      estimatedOG: "Estimated OG:",
      estimatedFG: "Estimated FG:",
      tolerance: "ABV Tolerance",
      sugarBreak: "1/3 SB",
      expectedABV: "Expected ABV:",
      nutrient: "Nutrient Protocol:",
      numberOfAdditions: "Number of Additions:",
      amount: "Amount per Addition:",
      total: "Total:",
      stabilizers: "Stabilizers",
      remaining: "Remaining YAN:",
      primary: "Primary Ingredients",
      weight: "Weight",
      volume: "Volume",
      secondary: "Secondary Ingredients",
      additives: "Additives",
      addAmount: "Amount",
      kmeta: "k-meta",
      ksorb: "k-sorb",
      primaryNotes: "Primary Notes",
      secondaryNotes: "Secondary Notes",
      details: "Details",
    },
  },
  de: {
    PDF: {
      title: "Rezept-PDF",
      pageTitle: "Rezeptbogen",
      totalVolume: "Gesamtvolumen",
      yeast: "Hefe",
      of: "von",
      with: "mit",
      tempRange: "Temperaturspanne",
      estimatedOG: "Geschätzte OG:",
      estimatedFG: "Geschätzte FG:",
      tolerance: "Alkoholtolerance",
      sugarBreak: "1/3 SB",
      expectedABV: "Erwarteter Alkoholgehalt:",
      nutrient: "Nährstoffprotokoll:",
      numberOfAdditions: "Anzahl an Gaben:",
      amount: "Menge pro Gabe:",
      total: "Gesamt:",
      stabilizers: "Stabilisatoren",
      remaining: "Verbleibende YAN:",
      primary: "Primärzutaten",
      weight: "Gewicht",
      volume: "Volumen",
      secondary: "Sekundärzutaten",
      additives: "Zusätze",
      addAmount: "Menge",
      kmeta: "Kaliumdisulfit",
      ksorb: "Kaliumsorbat",
      primaryNotes: "Notizen zur Primärgärung",
      secondaryNotes: "Notizen zur Sekundärgärung",
      details: "Details",
    },
  },
};

export const PDFTranslations = [PDF.en, PDF.de];
