const stabilizers = {
  en: {
    stabilizersHeading: "Stabilizers",
    adding: "Are you adding Stabilizers?",
    pH: "Are you taking a pH Reading?",
    yes: "Yes",
    no: "No",
    noSorb: "No Sorbate Needed!",
    kSorbate: "Potassium Sorbate",
    kSulfite: "Potassium Sulfite",
    kMeta: "Potassium Metabisulfite",
    additivesHeading: "Additives and Additional Ingredients",
    list: {
      redWineTannin: "Red Wine Tannin",
      ftRouge: "FT Rouge",
      optiRed: "Opti-Red",
      ftBlancSoft: "FT Blanc Soft",
      optiWhite: "Opti-White",
      tanninComplex: "Tannin Complex",
      tanninRicheExtra: "Tannin Riche Extra",
      citricAcid: "Citric Acid",
      malicAcid: "Malic Acid",
      tartaricAcid: "Tartaric Acid",
      bentonite: "Bentonite",
      chitosan: "Chitosan",
      kieselsol: "Kieselsol",
      sparkolloid: "Sparkolloid",
      pecticEnzyme: "Pectic Enzyme",
      lallzymeExV: "Lallzyme EX-V",
      lallzymeEx: "Lallzyme EX",
      lallzymeCMax: "Lallzyme C-Max",
      oakChips: "Oak Chips",
      oakSpirals: "Oak Spirals",
      oakCubes: "Oak Cubes",
      potassiumCarbonate: "Potassium Carbonate",
      campden: "Campden Tablets",
    },
  },
  de: {
    stabilizersHeading: "Stabilisatoren",
    adding: "Fügst du Stabilisatoren hinzu?",
    pH: "Misst du den pH-Wert?",
    yes: "Ja",
    no: "Nein",
    noSorb: "Kein Sorbat nötig!",
    kSorbate: "Kaliumsorbat",
    kSulfite: "Kaliumsulfit",
    kMeta: "Kaliumdisulfit",
    additivesHeading: "Zusätze und weitere Zutaten",
    list: {
      redWineTannin: "Rotwein-Tannin",
      ftRouge: "FT Rouge",
      optiRed: "Opti-Red",
      ftBlancSoft: "FT Blanc Soft",
      optiWhite: "Opti-White",
      tanninComplex: "Tannin Complex",
      tanninRicheExtra: "Tannin Riche Extra",
      citricAcid: "Zitronensäure",
      malicAcid: "Äpfelsäure",
      tartaricAcid: "Weinsäure",
      bentonite: "Bentonit",
      chitosan: "Chitosan",
      kieselsol: "Kieselsol",
      sparkolloid: "Sparkolloid",
      pecticEnzyme: "Pektinase",
      lallzymeExV: "Lallzyme EX-V",
      oakChips: "Eichenchips",
      oakSpirals: "Eichenspiralen",
      oakCubes: "Eichenwürfel",
      potassiumCarbonate: "Kaliumkarbonat",
    },
  },
};

export const stabilizersTranslations = [stabilizers.en, stabilizers.de];
