const unitsEN = {
  SUBMIT: "Submit",
  UNITS: "Units",
  BRIX: "Brix",
  DU: "Delle Units",
  ABV: "ABV",
  OG: "OG",
  FG: "FG",
  SG: "SG",
  PPM: "PPM",
  GAL: "Gallons",
  LBS: "lbs",
  G: "g",
  MG: "mg",
  KG: "kg",
  OZ: "oz",
  ML: "ml",
  FLOZ: "fl oz",
  QUARTS: "quarts",
  GALS: "gal",
  TSP: "tsp",
  TBSP: "tbsp",
  LIT: "Liters",
  FAR: "°F",
  CEL: "°C",
};

const unitsDE = {
  SUBMIT: "Abschicken",
  UNITS: "Einheiten",
  BRIX: "Brix",
  DU: "Delle-Einheiten",
  ABV: "Alk.%",
  OG: "OG",
  FG: "FG",
  SG: "SG",
  PPM: "PPM",
  LBS: "Pfund",
  KG: "kg",
  GAL: "Gallonen",
  LIT: "Liter",
  FAR: "°F",
  CEL: "°C",
};

export const unitsTranslations = [unitsEN, unitsDE];
